### ISSUE TITLE
Create game view

### ISSUE THREAD

**Issue by nkylstad** [acntech/node-multiplayer-snake#19]
Create a view that shows the actual game, with all the players' snakes, scoreboard, url to play and branding. 
Preliminary design:
![image](https://user-images.githubusercontent.com/1636323/40912032-bc259550-67f0-11e8-91ee-5a01ec1cba7f.png)

**Comment by BennyHoang** [comment]
Had some issues with understanding the structure. Currently looking into how to render the game board if first player has joined.
