### ISSUE TITLE
Create player view

### ISSUE THREAD

**Issue by nkylstad** [acntech/node-multiplayer-snake#20]
Create view that player sees on device. 
- View for playing the game (with controls, scores)
- View for starting the game after registering
- View for result after death/restart game
- View for registering (scan QR code)

Preliminary designs:

![image](https://user-images.githubusercontent.com/1636323/40912563-36e16cdc-67f2-11e8-9710-9902dcfd5f9a.png)

**Comment by sharizard** [comment]
Suggestion for "Registration"-view: 
- In the "Result"-view, let's ask the user if he or she wants to participate in our competition. If yes, user can enter an email address and/or phonenumber. 

Thoughts?
