### ISSUE TITLE
Bug: Tekst på Play-knappen er usynlig

### ISSUE THREAD

**Issue by ismarslomic** [acntech/node-multiplayer-snake#55]
Teksten på Play-knappen når man går til http://acn.zone er usynlig fordi den har samme farge som bakgrunnen. Du ser kun teksten når du har pekeren over knappen (onHover).

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by larshnordli** [comment]
Har fikset dette nå (dog kan det gjelde fargen på snake/spillernavnet er mørk ift tekstfeltet, men åpner et nytt issue på det)
