### ISSUE TITLE
Bytte tekst fra "Select nickname" til "Enter nickname"

### ISSUE THREAD

**Issue by ismarslomic** [acntech/node-multiplayer-snake#56]
Foreslår at vi endrer label-teksten for "Nickname"-inputfeltet fra "Select nickname" til "Enter nickname" på http://acn.zone, da brukeren ikke får noen valgmuligheter, men må taste inn nickname selv.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by larshnordli** [comment]
Har endret dette nå
