### ISSUE TITLE
Øke størrelsen på spill-knappene på mobilen

### ISSUE THREAD

**Issue by ismarslomic** [acntech/node-multiplayer-snake#58]
Jeg synes knappene (pilene opp/ned/høyre/venstre) er litt små og vanskelig å treffe på mobilen, når blikket må være oppe på storskjermen og man ikke følger med på mobil-skjermen.

Kan vi øke størrelsen/strekke ut pilknappene slik at det er enklere å treffe uten å se på mobilskjermen?

**Comment by sharizard** [comment]
@larshnordli er på saken! Vi har fått tilsendt skisser fra Jonathan (ligger på Teams), men har ikke rukket å implementere enda

**Comment by larshnordli** [comment]
Har gjort et første stunt på knappene nå. Lukker for nå, åpne igjen om de nye knappene oppleves som små fortsatt (de er WIP)
